#!/usr/bin/env sh

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &


# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

#####
#
# GLOBAL SETTINGS
#
#####

# Tiling options
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0
yabai -m config auto_balance                 off
yabai -m config split_ratio                  0.50

# Window modifications
yabai -m config window_origin_display        default
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_border                off
yabai -m config window_border_hidpi          off
yabai -m config window_border_blur           off
yabai -m config window_border_width          0
yabai -m config window_border_radius         0
yabai -m config window_opacity               off
yabai -m config active_window_opacity        0.9
yabai -m config normal_window_opacity        0.8

# Mouse options
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

#####
#
# SPACES
#
#####

yabai -m space 1 --label main --layout float
yabai -m space 2 --label term
yabai -m space 3 --label browser_work
yabai -m space 4 --label browser --layout stack

echo "yabai configuration loaded.."
